export class Empleado{
    nEmpleado:number | undefined;
    idJustificacion:number | undefined;
    activo:number | undefined;
    nombre:string | undefined;
    apellidos!: string;
    dni!: string;
    contrato:string | undefined;
    empresa:string | undefined;
    foto:string | undefined;
    telefono1:any;
    telefono2:any;
    email:any;
    descripcionPuesto:any;
    descripcion:any;
    turno:any;
    fechaInicio:any;
    fechaNacimiento:any;
    fechaReincorporacion:any;
    fechaBaja:any;
    categoriaE:any;
    id:number | undefined;
    puesto_id!: number;
    contrato_id!: number;
    idPlantilla!: number;
    bocadillo!: string;
    comentario!: string;
    idTurno!: number;
    idServicio!: number;
 }